# Base docker compose file used for production.
version: "3.9"

services:
  superservice:
    container_name: superservice
    image: superservice:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_RUNNING_IN_CONTAINER=true # to tell .net framework its running inside a container for better performance.
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=$CertPasswordPlain
    read_only: true # enforcing read-only for container filesystem
    volumes:
      - ./https:/https
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true # to prevent privilege escalation
    networks:
      - app_network

# setting up docker network
networks:
  app_network:
    driver: bridge